# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 0);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 3);
user_pref("browser.download.importedFromSqlite", true);
user_pref("browser.migration.version", 27);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 7);
user_pref("browser.search.countryCode", "MA");
user_pref("browser.search.region", "MA");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20150403142420");
user_pref("browser.slowStartup.averageTime", 2737);
user_pref("browser.slowStartup.samples", 4);
user_pref("browser.startup.homepage_override.buildID", "20150403142420");
user_pref("browser.startup.homepage_override.mstone", "37.0.1");
user_pref("datareporting.healthreport.nextDataSubmissionTime", "1429270433295");
user_pref("datareporting.policy.firstRunTime", "1429184033294");
user_pref("datareporting.sessions.current.activeTicks", 4);
user_pref("datareporting.sessions.current.clean", true);
user_pref("datareporting.sessions.current.firstPaint", 622);
user_pref("datareporting.sessions.current.main", 10);
user_pref("datareporting.sessions.current.sessionRestored", 712);
user_pref("datareporting.sessions.current.startTime", "1429184367150");
user_pref("datareporting.sessions.current.totalTime", 18);
user_pref("datareporting.sessions.currentIndex", 3);
user_pref("datareporting.sessions.previous.0", "{\"s\":1429184032996,\"a\":1,\"t\":7,\"c\":true,\"m\":10,\"fp\":2631,\"sr\":2979}");
user_pref("datareporting.sessions.previous.1", "{\"s\":1429184193453,\"a\":2,\"t\":9,\"c\":true,\"m\":11,\"fp\":629,\"sr\":706}");
user_pref("datareporting.sessions.previous.2", "{\"s\":1429184210543,\"a\":1,\"t\":9,\"c\":true,\"m\":5950,\"fp\":-1,\"sr\":-1}");
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.bootstrappedAddons", "{\"langpack-ar@firefox.mozilla.org\":{\"version\":\"37.0.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-ar@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-en-GB@firefox.mozilla.org\":{\"version\":\"37.0.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false},\"langpack-en-ZA@firefox.mozilla.org\":{\"version\":\"37.0.1\",\"type\":\"locale\",\"descriptor\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"multiprocessCompatible\":false}}");
user_pref("extensions.databaseSchema", 16);
user_pref("extensions.enabledAddons", "ubufox%40ubuntu.com:3.0,%7B972ce4c6-7e08-4474-a285-3208198ce6fd%7D:37.0.1");
user_pref("extensions.lastAppVersion", "37.0.1");
user_pref("extensions.lastPlatformVersion", "37.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.xpiState", "{\"app-global\":{\"langpack-ar@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-ar@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"37.0.1\",\"st\":1428072506000},\"{972ce4c6-7e08-4474-a285-3208198ce6fd}\":{\"d\":\"/usr/lib/firefox/browser/extensions/{972ce4c6-7e08-4474-a285-3208198ce6fd}\",\"e\":true,\"v\":\"37.0.1\",\"st\":1428478641000,\"mt\":1428071909000},\"langpack-en-GB@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-GB@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"37.0.1\",\"st\":1428072553000},\"langpack-en-ZA@firefox.mozilla.org\":{\"d\":\"/usr/lib/firefox/browser/extensions/langpack-en-ZA@firefox.mozilla.org.xpi\",\"e\":true,\"v\":\"37.0.1\",\"st\":1428072554000}},\"app-system-share\":{\"ubufox@ubuntu.com\":{\"d\":\"/usr/share/mozilla/extensions/{ec8030f7-c20a-464f-9b0e-13a3a9e97384}/ubufox@ubuntu.com\",\"e\":true,\"v\":\"3.0\",\"st\":1428392881000,\"mt\":1420839876000}}}");
user_pref("gecko.buildID", "20150403142420");
user_pref("gecko.mstone", "37.0.1");
user_pref("network.cookie.prefsMigrated", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("plugin.importedState", true);
user_pref("privacy.sanitize.migrateFx3Prefs", true);
user_pref("signon.importedFromSqlite", true);
user_pref("toolkit.startup.last_success", 1429184367);
user_pref("toolkit.telemetry.previousBuildID", "20150403142420");
